In [2]:
from torch.utils.data import Dataset
import torch
from torchvision import transforms

In [29]:
class toy_set(Dataset):
    def __init__(self, length=100, transform = None):
        self.x = 2*torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.len = length
        self.transform = transform
        
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len
        

In [14]:
dataset = toy_set()
dataset[1]

(tensor([2., 2.]), tensor([1.]))

In [15]:
dataset.__getitem__(1)

(tensor([2., 2.]), tensor([1.]))

In [11]:
toy_set.__getitem__(dataset, 1)

(tensor([2., 2.]), tensor([1.]))

In [16]:
len(dataset)

100

In [30]:
class add_mult(object):
    def __init__(self, addx=1, muly=1):
        self.addx= addx
        self.muly = muly
        
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x, y
        return sample

In [26]:
am = add_mult()
am((torch.tensor([1,2]), torch.tensor(1)))

(tensor([2, 3]), tensor(1))

In [31]:
dataset_ = toy_set(transform=add_mult())
dataset_[1]

(tensor([3., 3.]), tensor([1.]))

In [ ]:
# to apply multiple transforms we can use
# from torchvision import transforms 
# data = transforms.Compose([transform_1, transform_2])

In [32]:
# Create tranform class mult

class mult(object):
    
    # Constructor
    def __init__(self, mult = 100):
        self.mult = mult
        
    # Executor
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x * self.mult
        y = y * self.mult
        sample = x, y
        return sample

In [34]:
# Combine the add_mult() and mult()

data_transform = transforms.Compose([add_mult(), mult()])
print("The combination of transforms (Compose): ", data_transform)


The combination of transforms (Compose):  Compose(
)


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.3.1_trasform.png" width="500" alt="Compose PyTorch">


In [37]:
data_transform(dataset[0])

(tensor([300., 300.]), tensor([100.]))

In [38]:
x,y=dataset[0]
x_,y_=data_transform(dataset[0])
print( 'Original x: ', x, 'Original y: ', y)

print( 'Transformed x_:', x_, 'Transformed y_:', y_)

Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Transformed x_: tensor([300., 300.]) Transformed y_: tensor([100.])


In [39]:
# Create a new toy_set object with compose object as transform

compose_data_set = toy_set(transform = data_transform)

## Dataset


In [40]:
from PIL import Image
import pandas as pd
import os 
from matplotlib.pyplot import imshow 
from torch.utils.data import DataLoader, Dataset 

In [41]:
directory = "./data"
train_path = os.path.join(directory,"fashion-mnist_train.csv")
test_path = os.path.join(directory,"fashion-mnist_test.csv")

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

In [42]:
train.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [43]:
test.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       8  ...       103        87        56         0         0         0   
1       0  ...        34         0         0         0         0         0   
2      99  ...         0         0         0         0        63        53   
3       0  ...       137       126       140         0       133       224   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2        31         0         0         0  
3       222        56         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
#dataset class for images using path instead of retriecing all images
class Dataset(Dataset):
    def __init__(self, csv_file, data_dir, transform = None):
        self.transform = transform
        self.data_dir = data_dir
        data_dircsv_file = os.path.join(data_dir, csv_file)
        
        self.data__name = pd.read_csv(data_dircsv_file)
        self.len = self.data__name.shape[0]
        
    def __len__(self):
        return self.len
    def __getitem__(self, idx):
        image_name = os.path.join(self.data_dir,self.data__name.iloc[idx, 1])
        image = Image.open(image_name)
        
        y = self.data__name.iloc[idx, 0]
        
        if self.transform:
            image = self.transform(image)
        return image, y

### TorchVision Transforms

In [ ]:
transforms.CenterCrop(20)
transforms.ToTensor()
cropped_tensor_transform = transforms.Compose([transforms.CenterCrop(20), transforms.ToTensor])
dataset = Dataset(transform=cropped_tensor_transform)

### TorchVision Datasets

In [4]:
import torchvision.datasets as dsets

dataset = dsets.MNIST( root="./data", train=False, download=True, transform=transforms.ToTensor())

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:10<00:00, 954394.31it/s] 


Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 201946.00it/s]


Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:02<00:00, 570534.78it/s]


Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 2252101.76it/s]

Extracting ./data\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data\MNIST\raw

